### ISSUE TITLE
Can Token Row allowed to customise the table appearance ?

### ISSUE THREAD

**Issue by iOSUser110** [EurekaCommunity/TokenRow#1]
The table appears on search character,
Can we change the background color of this table view, change the font and text position.
Waiting for your relpy....need this in urgent

and also there is content size issue for table of TokenTableROw. Cant scroll last records.

**Comment by mats-claassen** [comment]
Yes you can. Read through [this section](https://github.com/EurekaCommunity/TokenRow#tokentablerow) of the Readme to see how you can do it.
