### ISSUE TITLE
Open dropdown on click

### ISSUE THREAD

**Issue by SpajicM** [EurekaCommunity/TokenRow#14]
Is it possible to make token results show on click, before anything is typed?

**Comment by mats-claassen** [comment]
Currently the TokenRow shows no options if the text is empty. 

To change this you will have to subclass `CollectionTokenCell` or `TableTokenCell` to change the delegate methods like `func tokenInputView(_ aView: CLTokenInputView, didChangeText text: String?)` and `tokenInputViewDidBeginEditing(_ view: CLTokenInputView)`

**Comment by SpajicM** [comment]
Alright, and after doing so, how do I change TokenRow to use MyTableViewTokenCell instead of in-built one?

**Comment by mats-claassen** [comment]
Read through [this Readme section](https://github.com/EurekaCommunity/TokenRow#tokenaccessoryrow)
