### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by Nolascoin** [EurekaCommunity/TokenRow#17]
Although you may think these warnings can be ignored, they can later on cause xcodebuild to fail with error code 65 when using fastlane.  It's a head scratcher indeed.

Cast from 'RowOf<Set<T>>?' to unrelated type '_TokenRow<T, CollectionTokenCell<T, CollectionViewCell>>' always fails

Cast from 'RowOf<Set<T>>?' to unrelated type '_TokenRow<T, CollectionTokenCell<T, CollectionViewCell>>' always fails

**Comment by Nolascoin** [comment]
Cast from 'RowOf<Set<T>>?' to unrelated type '_TokenRow<T, TableTokenCell<T, TableViewCell>>' always fails

Cast from 'RowOf<Set<T>>?' to unrelated type '_TokenRow<T, TableTokenCell<T, TableViewCell>>' always fails

**Comment by mats-claassen** [comment]
Well, the warnings are wrong because the casting succeeds. I think this is a compiler issue

**Comment by Nolascoin** [comment]
Closing, compiler issue.
