### ISSUE TITLE
How to setup previous values - setting $value not working.

### ISSUE THREAD

**Issue by bvelasquez** [EurekaCommunity/TokenRow#18]
I want to display the options previously selected to the user.

```
<<< TokenTableRow<CategoryOption>() {
                $0.placeholder = "Choose Categories"
                $0.options = categoryOptions
                $0.value = entryCategories
                $0.tag = "categories"
            }
```

entryCategories is Set<CategoryOption>().  None of the objects in the Set are displayed.  CategoryOption is TokenSearchable.

**Comment by mats-claassen** [comment]
I made a PR with a fix for this. Could you test it from that branch to see if it works for you?

**Comment by bvelasquez** [comment]
@mats-claassen This fixed the issue and the values are displayed.  However, when deleting the tokens via backspacing, and then changing focus to another field or selecting 'Done', the deleted values come back.  Not sure if this is related to the fix.

**Comment by bvelasquez** [comment]
This fixes the issue.  Thank you.
