### ISSUE TITLE
Use it standalone 

### ISSUE THREAD

**Issue by reshadf** [EurekaCommunity/TokenRow#20]
Hi is it possible to use the "view" to display the tokenized view inside a cell without using other Eureka components as a standalone component? I can't seem to find it in the docs :)

**Comment by mats-claassen** [comment]
TokenRow is to be used in Eureka forms. It was not designed to be used in a simple UITableView, although it is a `UITableViewCell`. You could try that but I guess you are better of using `CLTokenInputView` as your token view (or any other library) and creating a UITableViewCell with that subview. You can base it on TokenRow's code.
