### ISSUE TITLE
Installing with Eureka 4.0

### ISSUE THREAD

**Issue by Simon-Colley** [EurekaCommunity/TokenRow#6]
Hi

BTW Thanks for Eureka :)

I am using Eureka 4.0, I would like to use TokenRow with it.
TokenRow pod spec is for ~>3.0 so pod install gives the following error:

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Eureka (= 4.0.0)` required by `Podfile`
- `Eureka (= 4.0.0)` required by `Podfile`
- `Eureka (= 4.0.0)` required by `Podfile`
- `Eureka (= 4.0.0)` required by `Podfile.lock`
- `Eureka (~> 3.0)` required by `TokenRow (1.2.0)`

Xcode version = 9.0.1
iOS SDK = 11 (Deployment target = 10.2)

Is there a workaround for this atm ?

**Comment by shaunjacobsen** [comment]
I am also having the same issue.

**Comment by mats-claassen** [comment]
Fixed
